{
  "url": "https://developers.eduzz.com/api/openapi",
  "spec": {
    "openapi": "3.1.0",
    "info": {
      "title": "Eduzz Public API",
      "description": "Esta é a definição da api pública da Eduzz",
      "termsOfService": "https://example.com/terms/",
      "contact": {
        "name": "API Support",
        "url": "https://discord.gg/VxYf5y5Ry3",
        "email": "support@eduzz.com"
      },
      "license": {
        "name": "Apache 2.0",
        "url": "https://www.apache.org/licenses/LICENSE-2.0.html"
      },
      "version": "2.0.0"
    },
    "servers": [
      {
        "url": "https://api.eduzz.com",
        "description": "Production"
      }
    ],
    "webhooks": {
      "alpaclass.student_certificate_accessed": {
        "post": {
        }
      },
      "alpaclass.student_comment_created": {
        "post": {
        }
      },
      "alpaclass.student_lesson_unmarked_as_favorite": {
        "post": {
        }
      },
      "alpaclass.student_lesson_unfinished": {
        "post": {
        }
      },
      "alpaclass.student_course_unfinished": {
        "post": {
        }
      },
      "alpaclass.student_module_unfinished": {
        "post": {
        }
      },
      "alpaclass.student_lesson_marked_as_favorite": {
        "post": {
        }
      },
      "alpaclass.student_course_finished": {
        "post": {
        }
      },
      "alpaclass.student_module_finished": {
        "post": {
        }
      },
      "alpaclass.student_created": {
        "post": {
        }
      },
      "alpaclass.student_lesson_finished": {
        "post": {
        }
      },
      "alpaclass.student_lesson_last_seen": {
        "post": {
        }
      },
      "alpaclass.student_course_last_seen": {
        "post": {
        }
      },
      "blinket.ticket_edited": {
        "post": {
        }
      },
      "blinket.attendance_checkin": {
        "post": {
        }
      },
      "blinket.attendance_canceled": {
        "post": {
        }
      },
      "blinket.attendances_printed": {
        "post": {
        }
      },
      "blinket.attendance_tag_changed": {
        "post": {
        }
      },
      "blinket.attendance_added": {
        "post": {
        }
      },
      "blinket.attendance_assigned": {
        "post": {
        }
      },
      "blinket.attendance_edited": {
        "post": {
        }
      },
      "myeduzz.contract_updated": {
        "post": {
        }
      },
      "myeduzz.contract_created": {
        "post": {
        }
      },
      "myeduzz.contract_bankslip_attempted": {
        "post": {
        }
      },
      "myeduzz.contract_card_attempted": {
        "post": {
        }
      },
      "myeduzz.contract_pix_attempted": {
        "post": {
        }
      },
      "myeduzz.contract_eduzz_balance_attempted": {
        "post": {
        }
      },
      "myeduzz.commission_processed": {
        "post": {
        }
      },
      "myeduzz.invoice_opened": {
        "post": {
        }
      },
      "myeduzz.invoice_scheduled": {
        "post": {
        }
      },
      "myeduzz.invoice_waiting_payment": {
        "post": {
        }
      },
      "myeduzz.invoice_waiting_refund": {
        "post": {
        }
      },
      "myeduzz.invoice_canceled": {
        "post": {
        }
      },
      "myeduzz.invoice_chargeback": {
        "post": {
        }
      },
      "myeduzz.invoice_recovering": {
        "post": {
        }
      },
      "myeduzz.invoice_expired": {
        "post": {
        }
      },
      "myeduzz.invoice_negotiated": {
        "post": {
        }
      },
      "myeduzz.invoice_paid": {
        "post": {
        }
      },
      "myeduzz.invoice_refunded": {
        "post": {
        }
      },
      "nutror.inactive_student": {
        "post": {
        }
      },
      "nutror.notation_created": {
        "post": {
        }
      },
      "nutror.file_downloaded": {
        "post": {
        }
      },
      "nutror.enrollment_created": {
        "post": {
        }
      },
      "nutror.lesson_rated": {
        "post": {
        }
      },
      "nutror.lesson_watched": {
        "post": {
        }
      },
      "nutror.lesson_started": {
        "post": {
        }
      },
      "nutror.lesson_saved": {
        "post": {
        }
      },
      "nutror.comment_created": {
        "post": {
        }
      },
      "nutror.comment_deleted": {
        "post": {
        }
      },
      "nutror.comment_replied": {
        "post": {
        }
      },
      "nutror.module_completed": {
        "post": {
        }
      },
      "nutror.learner_help": {
        "post": {
        }
      },
      "nutror.certificate_viewed": {
        "post": {
        }
      },
      "nutror.community_viewed": {
        "post": {
        }
      },
      "safevideo.encoder_error": {
        "post": {
        }
      },
      "safevideo.encoder_waiting": {
        "post": {
        }
      },
      "safevideo.encoder_finished": {
        "post": {
        }
      },
      "safevideo.encoder_started": {
        "post": {
        }
      },
      "safevideo.upload_error": {
        "post": {
        }
      },
      "safevideo.upload_canceled": {
        "post": {
        }
      },
      "safevideo.upload_finished": {
        "post": {
        }
      },
      "safevideo.upload_started": {
        "post": {
        }
      },
      "sun.cart_abandonment": {
        "post": {
        }
      }
    },
    "paths": {
      "/accounts/v1/me": {
        "get": {
          "operationId": "getaccountsv1me",
          "summary": "Retorna dados do usuário logado.",
          "tags": [
            "Accounts"
          ],
          "security": [
            {
              "eduzz_auth": [
                "none"
              ]
            }
          ]
        }
      },
      "/alpaclass/v1/producer/teams/:teamId/students": {
        "post": {
          "operationId": "postalpaclassv1producerteamsteamIdstudents",
          "summary": "Cria um novo aluno em uma escola.",
          "tags": [
            "Alpaclass"
          ],
          "security": [
            {
              "eduzz_auth": [
                "alpaclass_team_write"
              ]
            }
          ]
        },
        "get": {
          "operationId": "getalpaclassv1producerteamsteamIdstudents",
          "summary": "Listar alunos da escola",
          "tags": [
            "Alpaclass"
          ],
          "security": [
            {
              "eduzz_auth": [
                "alpaclass_student_read"
              ]
            }
          ]
        }
      },
      "/alpaclass/v1/producer/teams/:teamId/students/:studentId/enrollments": {
        "get": {
          "operationId": "getalpaclassv1producerteamsteamIdstudentsstudentIdenrollments",
          "summary": "Retorna a lista de matrículas de um aluno específico em uma escola.",
          "tags": [
            "Alpaclass"
          ],
          "security": [
            {
              "eduzz_auth": [
                "alpaclass_student_read"
              ]
            }
          ]
        }
      },
      "/alpaclass/v1/producer/teams/:teamId/deliveries/:deliveryId/courses": {
        "get": {
          "operationId": "getalpaclassv1producerteamsteamIddeliveriesdeliveryIdcourses",
          "summary": "Listar os cursos da entrega",
          "tags": [
            "Alpaclass"
          ],
          "security": [
            {
              "eduzz_auth": [
                "alpaclass_delivery_read"
              ]
            }
          ]
        }
      },
      "/alpaclass/v1/producer/teams/:teamId/deliveries/:deliveryId": {
        "get": {
          "operationId": "getalpaclassv1producerteamsteamIddeliveriesdeliveryId",
          "summary": "Listar os detalhes da entrega",
          "tags": [
            "Alpaclass"
          ],
          "security": [
            {
              "eduzz_auth": [
                "alpaclass_delivery_read"
              ]
            }
          ]
        }
      },
      "/alpaclass/v1/producer/teams/:teamId/deliveries": {
        "get": {
          "operationId": "getalpaclassv1producerteamsteamIddeliveries",
          "summary": "Listar as entregas da escola",
          "tags": [
            "Alpaclass"
          ],
          "security": [
            {
              "eduzz_auth": [
                "alpaclass_delivery_read"
              ]
            }
          ]
        }
      },
      "/alpaclass/v1/producer/teams": {
        "get": {
          "operationId": "getalpaclassv1producerteams",
          "summary": "Listar minhas escolas",
          "tags": [
            "Alpaclass"
          ],
          "security": [
            {
              "eduzz_auth": [
                "alpaclass_team_read"
              ]
            }
          ]
        }
      },
      "/blinket/v1/events/:id": {
        "get": {
          "operationId": "getblinketv1eventsid",
          "summary": "Detalhes do evento",
          "tags": [
            "Blinket"
          ],
          "security": [
            {
              "eduzz_auth": [
                "blinket_read"
              ]
            }
          ]
        }
      },
      "/blinket/v1/events": {
        "get": {
          "operationId": "getblinketv1events",
          "summary": "Uma lista completa dos seus eventos",
          "tags": [
            "Blinket"
          ],
          "security": [
            {
              "eduzz_auth": [
                "blinket_read"
              ]
            }
          ]
        }
      },
      "/blinket/v1/attendance-tags/:id": {
        "put": {
          "operationId": "putblinketv1attendancetagsid",
          "summary": "Altera um marcador existente",
          "tags": [
            "Blinket"
          ],
          "security": [
            {
              "eduzz_auth": [
                "blinket_write"
              ]
            }
          ]
        },
        "delete": {
          "operationId": "deleteblinketv1attendancetagsid",
          "summary": "Remove um marcador e o desvincula de todos os participantes que o possuem",
          "tags": [
            "Blinket"
          ],
          "security": [
            {
              "eduzz_auth": [
                "blinket_write"
              ]
            }
          ]
        }
      },
      "/blinket/v1/attendance-tags": {
        "post": {
          "operationId": "postblinketv1attendancetags",
          "summary": "Cria um novo marcador que poderá ser usado em diferentes eventos",
          "tags": [
            "Blinket"
          ],
          "security": [
            {
              "eduzz_auth": [
                "blinket_write"
              ]
            }
          ]
        },
        "get": {
          "operationId": "getblinketv1attendancetags",
          "summary": "Obtém uma lista de todos os marcadores cadastrados",
          "tags": [
            "Blinket"
          ],
          "security": [
            {
              "eduzz_auth": [
                "blinket_read"
              ]
            }
          ]
        }
      },
      "/blinket/v1/attendance-tags/:id/attendance-list": {
        "delete": {
          "operationId": "deleteblinketv1attendancetagsidattendancelist",
          "summary": "Remove um marcador de um ou mais participantes",
          "tags": [
            "Blinket"
          ],
          "security": [
            {
              "eduzz_auth": [
                "blinket_write"
              ]
            }
          ]
        },
        "get": {
          "operationId": "getblinketv1attendancetagsidattendancelist",
          "summary": "Obtém todos os ids de participantes vinculados a um marcador",
          "tags": [
            "Blinket"
          ],
          "security": [
            {
              "eduzz_auth": [
                "blinket_write"
              ]
            }
          ]
        },
        "post": {
          "operationId": "postblinketv1attendancetagsidattendancelist",
          "summary": "Atribui um marcador a um ou mais participantes",
          "tags": [
            "Blinket"
          ],
          "security": [
            {
              "eduzz_auth": [
                "blinket_read"
              ]
            }
          ]
        }
      },
      "/blinket/v1/attendance-list/add-manually": {
        "post": {
          "operationId": "postblinketv1attendancelistaddmanually",
          "summary": "Adicionar participante",
          "tags": [
            "Blinket"
          ],
          "security": [
            {
              "eduzz_auth": [
                "blinket_read",
                "blinket_write"
              ]
            }
          ]
        }
      },
      "/blinket/v1/attendance-list/update-by-invitekey/:id": {
        "put": {
          "operationId": "putblinketv1attendancelistupdatebyinvitekeyid",
          "summary": "Modifica os dados de titularidade do ingresso, como Nome, E-mail, Telefone e Documento",
          "tags": [
            "Blinket"
          ],
          "security": [
            {
              "eduzz_auth": [
                "blinket_read",
                "blinket_write"
              ]
            }
          ]
        }
      },
      "/blinket/v1/attendance-list/check-in": {
        "put": {
          "operationId": "putblinketv1attendancelistcheckin",
          "summary": "Alterar check-in",
          "tags": [
            "Blinket"
          ],
          "security": [
            {
              "eduzz_auth": [
                "blinket_write"
              ]
            }
          ]
        }
      },
      "/blinket/v1/attendance-list/by-event/:id": {
        "get": {
          "operationId": "getblinketv1attendancelistbyeventid",
          "summary": "Lista os participantes do evento",
          "tags": [
            "Blinket"
          ],
          "security": [
            {
              "eduzz_auth": [
                "blinket_read"
              ]
            }
          ]
        }
      },
      "/blinket/v1/attendance-list/resend-ticket-email": {
        "post": {
          "operationId": "postblinketv1attendancelistresendticketemail",
          "summary": "Reenviar ingresso por e-mail",
          "tags": [
            "Blinket"
          ],
          "security": [
            {
              "eduzz_auth": [
                "blinket_write"
              ]
            }
          ]
        }
      },
      "/sun/v1/cart": {
        "post": {
          "operationId": "postsunv1cart",
          "summary": "O endpoint permite a criação de um carrinho de compras no checkout, onde vários itens são adicionados e interpretados como um único item, com seus valores somados e exibidos como um total consolidado, é possível criar um carrinho contendo apenas produtos de uma mesma conta.",
          "tags": [
            "Checkout Sun"
          ],
          "security": [
            {
              "eduzz_auth": [
                "sun_cart_write"
              ]
            }
          ]
        }
      },
      "/heycamp/v1/comments/on-post/:postId/community/:communityId": {
        "get": {
          "operationId": "getheycampv1commentsonpostpostIdcommunitycommunityId",
          "summary": "Listar comentários de uma publicação",
          "tags": [
            "HeyCamp"
          ],
          "security": [
            {
              "eduzz_auth": [
                "heycamp_read_comments"
              ]
            }
          ]
        }
      },
      "/heycamp/v1/invitations": {
        "post": {
          "operationId": "postheycampv1invitations",
          "summary": "Cria o convite",
          "tags": [
            "HeyCamp"
          ],
          "security": [
            {
              "eduzz_auth": [
                "heycamp_write_invitations"
              ]
            }
          ]
        }
      },
      "/heycamp/v1/invitations/:communityId": {
        "get": {
          "operationId": "getheycampv1invitationscommunityId",
          "summary": "Listar convites",
          "tags": [
            "HeyCamp"
          ],
          "security": [
            {
              "eduzz_auth": [
                "heycamp_read_invitations"
              ]
            }
          ]
        }
      },
      "/heycamp/v1/spaces/community/:communityId": {
        "get": {
          "operationId": "getheycampv1spacescommunitycommunityId",
          "summary": "Listar espaços",
          "tags": [
            "HeyCamp"
          ],
          "security": [
            {
              "eduzz_auth": [
                "heycamp_read_spaces"
              ]
            }
          ]
        }
      },
      "/heycamp/v1/members/:memberId": {
        "put": {
          "operationId": "putheycampv1membersmemberId",
          "summary": "Atualiza dados do membro",
          "tags": [
            "HeyCamp"
          ],
          "security": [
            {
              "eduzz_auth": [
                "heycamp_write_members"
              ]
            }
          ]
        }
      },
      "/heycamp/v1/members/:memberId/community/:communityId": {
        "delete": {
          "operationId": "deleteheycampv1membersmemberIdcommunitycommunityId",
          "summary": "Excluir membro específico de uma comunidade",
          "tags": [
            "HeyCamp"
          ],
          "security": [
            {
              "eduzz_auth": [
                "heycamp_write_members"
              ]
            }
          ]
        },
        "get": {
          "operationId": "getheycampv1membersmemberIdcommunitycommunityId",
          "summary": "Listar detalhes do membro associado à comunidade",
          "tags": [
            "HeyCamp"
          ],
          "security": [
            {
              "eduzz_auth": [
                "heycamp_read_members"
              ]
            }
          ]
        }
      },
      "/heycamp/v1/members/bulk": {
        "delete": {
          "operationId": "deleteheycampv1membersbulk",
          "summary": "Executa exclusão em massa de membros",
          "tags": [
            "HeyCamp"
          ],
          "security": [
            {
              "eduzz_auth": [
                "heycamp_write_members"
              ]
            }
          ]
        }
      },
      "/heycamp/v1/members/community/:communityId": {
        "get": {
          "operationId": "getheycampv1memberscommunitycommunityId",
          "summary": "Listar os membros associados à comunidade",
          "tags": [
            "HeyCamp"
          ],
          "security": [
            {
              "eduzz_auth": [
                "heycamp_read_members"
              ]
            }
          ]
        }
      },
      "/heycamp/v1/members/community/:communityId/comments": {
        "get": {
          "operationId": "getheycampv1memberscommunitycommunityIdcomments",
          "summary": "Listar todos membros que comentaram em alguma publicação em um determinado período",
          "tags": [
            "HeyCamp"
          ],
          "security": [
            {
              "eduzz_auth": [
                "heycamp_read_members"
              ]
            }
          ]
        }
      },
      "/heycamp/v1/members/community/:communityId/likes": {
        "get": {
          "operationId": "getheycampv1memberscommunitycommunityIdlikes",
          "summary": "Listar todos membros que curtiram alguma publicação em um determinado período",
          "tags": [
            "HeyCamp"
          ],
          "security": [
            {
              "eduzz_auth": [
                "heycamp_read_members"
              ]
            }
          ]
        }
      },
      "/heycamp/v1/posts/:postId/community/:communityId": {
        "get": {
          "operationId": "getheycampv1postspostIdcommunitycommunityId",
          "summary": "Buscar post de uma comunidade",
          "tags": [
            "HeyCamp"
          ],
          "security": [
            {
              "eduzz_auth": [
                "heycamp_read_posts"
              ]
            }
          ]
        }
      },
      "/heycamp/v1/posts/community/:communityId": {
        "get": {
          "operationId": "getheycampv1postscommunitycommunityId",
          "summary": "Listar posts de uma comunidade",
          "tags": [
            "HeyCamp"
          ],
          "security": [
            {
              "eduzz_auth": [
                "heycamp_read_posts"
              ]
            }
          ]
        }
      },
      "/heycamp/v1/posts/community/:communityId/top/commented": {
        "get": {
          "operationId": "getheycampv1postscommunitycommunityIdtopcommented",
          "summary": "Listar os 5 posts mais comentados da comunidade por um determinado período",
          "tags": [
            "HeyCamp"
          ],
          "security": [
            {
              "eduzz_auth": [
                "heycamp_read_posts"
              ]
            }
          ]
        }
      },
      "/heycamp/v1/posts/community/:communityId/top/liked": {
        "get": {
          "operationId": "getheycampv1postscommunitycommunityIdtopliked",
          "summary": "Listar os 5 posts com mais curtidas da comunidade por um determinado período",
          "tags": [
            "HeyCamp"
          ],
          "security": [
            {
              "eduzz_auth": [
                "heycamp_read_posts"
              ]
            }
          ]
        }
      },
      "/heycamp/v1/posts/community/:communityId/total/comments": {
        "get": {
          "operationId": "getheycampv1postscommunitycommunityIdtotalcomments",
          "summary": "Listar o total de comentários da comunidade por um determinado período",
          "tags": [
            "HeyCamp"
          ],
          "security": [
            {
              "eduzz_auth": [
                "heycamp_read_posts"
              ]
            }
          ]
        }
      },
      "/myeduzz/v1/affiliates": {
        "get": {
          "operationId": "getmyeduzzv1affiliates",
          "summary": "Listagem de todos os afiliados do produtor com base nos filtros fornecidos.",
          "tags": [
            "MyEduzz"
          ],
          "security": [
            {
              "eduzz_auth": [
                "myeduzz_affiliates_read"
              ]
            }
          ]
        }
      },
      "/myeduzz/v1/subscriptions/:id/recurring-date": {
        "put": {
          "operationId": "putmyeduzzv1subscriptionsidrecurringdate",
          "summary": "Modifica o dia de cobrança de uma assinatura específica.",
          "tags": [
            "MyEduzz"
          ],
          "security": [
            {
              "eduzz_auth": [
                "myeduzz_subscriptions_write"
              ]
            }
          ]
        }
      },
      "/myeduzz/v1/subscriptions/bulk-cancel": {
        "post": {
          "operationId": "postmyeduzzv1subscriptionsbulkcancel",
          "summary": "Realiza o cancelamento em massa de contratos.",
          "tags": [
            "MyEduzz"
          ],
          "security": [
            {
              "eduzz_auth": [
                "myeduzz_subscriptions_write"
              ]
            }
          ]
        }
      },
      "/myeduzz/v1/subscriptions/:id": {
        "get": {
          "operationId": "getmyeduzzv1subscriptionsid",
          "summary": "Obtém os detalhes de uma assinatura por id",
          "tags": [
            "MyEduzz"
          ],
          "security": [
            {
              "eduzz_auth": [
                "myeduzz_subscriptions_read"
              ]
            }
          ]
        }
      },
      "/myeduzz/v1/subscriptions": {
        "get": {
          "operationId": "getmyeduzzv1subscriptions",
          "summary": "Obtém os detalhes das assinaturas por intervalo de data",
          "tags": [
            "MyEduzz"
          ],
          "security": [
            {
              "eduzz_auth": [
                "myeduzz_subscriptions_read"
              ]
            }
          ]
        }
      },
      "/myeduzz/v1/subscriptions/customers/:email": {
        "get": {
          "operationId": "getmyeduzzv1subscriptionscustomersemail",
          "summary": "Obtém os detalhes do cliente via email",
          "tags": [
            "MyEduzz"
          ],
          "security": [
            {
              "eduzz_auth": [
                "myeduzz_subscriptions_read"
              ]
            }
          ]
        }
      },
      "/myeduzz/v1/subscriptions/:id/invoices": {
        "get": {
          "operationId": "getmyeduzzv1subscriptionsidinvoices",
          "summary": "Obtém as faturas de uma assinatura.",
          "tags": [
            "MyEduzz"
          ],
          "security": [
            {
              "eduzz_auth": [
                "myeduzz_subscriptions_read"
              ]
            }
          ]
        }
      },
      "/myeduzz/v1/subscriptions/:id/reactivate": {
        "post": {
          "operationId": "postmyeduzzv1subscriptionsidreactivate",
          "summary": "Realiza a reativação de um contrato",
          "tags": [
            "MyEduzz"
          ],
          "security": [
            {
              "eduzz_auth": [
                "myeduzz_subscriptions_write"
              ]
            }
          ]
        }
      },
      "/myeduzz/v1/subscriptions/:id/send-card-change-email": {
        "put": {
          "operationId": "putmyeduzzv1subscriptionsidsendcardchangeemail",
          "summary": "Envia email para alteração do cartão de pagamento de um contrato específico",
          "tags": [
            "MyEduzz"
          ],
          "security": [
            {
              "eduzz_auth": [
                "myeduzz_subscriptions_write"
              ]
            }
          ]
        }
      },
      "/myeduzz/v1/customers/:email": {
        "get": {
          "operationId": "getmyeduzzv1customersemail",
          "summary": "Obtém detalhes de um comprador",
          "tags": [
            "MyEduzz"
          ],
          "security": [
            {
              "eduzz_auth": [
                "myeduzz_customers_read"
              ]
            }
          ]
        }
      },
      "/myeduzz/v1/customers": {
        "get": {
          "operationId": "getmyeduzzv1customers",
          "summary": "Listagem de todos os compradores com base nos filtros fornecidos.",
          "tags": [
            "MyEduzz"
          ],
          "security": [
            {
              "eduzz_auth": [
                "myeduzz_customers_read"
              ]
            }
          ]
        }
      },
      "/myeduzz/v1/financial/affiliate/fiscal-documents/:id/change-status": {
        "patch": {
          "operationId": "patchmyeduzzv1financialaffiliatefiscaldocumentsidchangestatus",
          "summary": "Atualiza o status de um documento fiscal emitido a um afiliado",
          "tags": [
            "MyEduzz"
          ],
          "security": [
            {
              "eduzz_auth": [
                "myeduzz_financial_write"
              ]
            }
          ]
        }
      },
      "/myeduzz/v1/financial/buyer/fiscal-documents/:id/change-status": {
        "patch": {
          "operationId": "patchmyeduzzv1financialbuyerfiscaldocumentsidchangestatus",
          "summary": "Atualiza o status de um documento fiscal emitido a um Comprador",
          "tags": [
            "MyEduzz"
          ],
          "security": [
            {
              "eduzz_auth": [
                "myeduzz_financial_write"
              ]
            }
          ]
        }
      },
      "/myeduzz/v2/financial/statement": {
        "get": {
          "operationId": "getmyeduzzv2financialstatement",
          "summary": "Retorna o extrato financeiro com base nos filtros fornecidos.",
          "tags": [
            "MyEduzz"
          ],
          "security": [
            {
              "eduzz_auth": [
                "myeduzz_financial_read"
              ]
            }
          ]
        }
      },
      "/myeduzz/v1/financial/affiliate/fiscal-documents": {
        "get": {
          "operationId": "getmyeduzzv1financialaffiliatefiscaldocuments",
          "summary": "Lista documentos fiscais do afiliado com base em critérios como datas, status, venda e conteúdo, detalhando informações fiscais e do cliente.",
          "tags": [
            "MyEduzz"
          ],
          "security": [
            {
              "eduzz_auth": [
                "myeduzz_financial_read"
              ]
            }
          ]
        }
      },
      "/myeduzz/v1/financial/buyer/fiscal-documents": {
        "get": {
          "operationId": "getmyeduzzv1financialbuyerfiscaldocuments",
          "summary": "Lista documentos fiscais do comprador com base em critérios como datas, status, venda e conteúdo, detalhando informações fiscais e do cliente.",
          "tags": [
            "MyEduzz"
          ],
          "security": [
            {
              "eduzz_auth": [
                "myeduzz_financial_read"
              ]
            }
          ]
        }
      },
      "/myeduzz/v1/financial/transfers": {
        "get": {
          "operationId": "getmyeduzzv1financialtransfers",
          "summary": "Obtém detalhes das transferências realizadas com base nos filtros fornecidos.",
          "tags": [
            "MyEduzz"
          ],
          "security": [
            {
              "eduzz_auth": [
                "myeduzz_financial_read"
              ]
            }
          ]
        }
      },
      "/myeduzz/v1/products/:id/campaigns": {
        "get": {
          "operationId": "getmyeduzzv1productsidcampaigns",
          "summary": "Obtém as campanhas de um produto ",
          "tags": [
            "MyEduzz"
          ],
          "security": [
            {
              "eduzz_auth": [
                "myeduzz_products_read"
              ]
            }
          ]
        }
      },
      "/myeduzz/v1/products/coupons": {
        "get": {
          "operationId": "getmyeduzzv1productscoupons",
          "summary": "Listagem de todos os cupons de produtos do produtor",
          "tags": [
            "MyEduzz"
          ],
          "security": [
            {
              "eduzz_auth": [
                "myeduzz_products_read"
              ]
            }
          ]
        }
      },
      "/myeduzz/v1/products/:id": {
        "get": {
          "operationId": "getmyeduzzv1productsid",
          "summary": "Obtém os detalhes de um produto específico",
          "tags": [
            "MyEduzz"
          ],
          "security": [
            {
              "eduzz_auth": [
                "myeduzz_products_read"
              ]
            }
          ]
        }
      },
      "/myeduzz/v1/products": {
        "get": {
          "operationId": "getmyeduzzv1products",
          "summary": "Listagem de todos os produtos do produtor",
          "tags": [
            "MyEduzz"
          ],
          "security": [
            {
              "eduzz_auth": [
                "myeduzz_products_read"
              ]
            }
          ]
        }
      },
      "/myeduzz/v1/products/:id/offers": {
        "get": {
          "operationId": "getmyeduzzv1productsidoffers",
          "summary": "Obtém as ofertas de um produto",
          "tags": [
            "MyEduzz"
          ],
          "security": [
            {
              "eduzz_auth": [
                "myeduzz_products_read"
              ]
            }
          ]
        }
      },
      "/myeduzz/v1/products/:id/partners": {
        "get": {
          "operationId": "getmyeduzzv1productsidpartners",
          "summary": "Obtém os parceiros de um produto",
          "tags": [
            "MyEduzz"
          ],
          "security": [
            {
              "eduzz_auth": [
                "myeduzz_products_read"
              ]
            }
          ]
        }
      },
      "/myeduzz/v1/sales/:id": {
        "get": {
          "operationId": "getmyeduzzv1salesid",
          "summary": "Obtém detalhes de uma venda específica",
          "tags": [
            "MyEduzz"
          ],
          "security": [
            {
              "eduzz_auth": [
                "myeduzz_sales_read"
              ]
            }
          ]
        }
      },
      "/myeduzz/v1/sales": {
        "get": {
          "operationId": "getmyeduzzv1sales",
          "summary": "Obtém uma lista detalhada de vendas com base nos filtros fornecidos",
          "tags": [
            "MyEduzz"
          ],
          "security": [
            {
              "eduzz_auth": [
                "myeduzz_sales_read"
              ]
            }
          ]
        }
      },
      "/myeduzz/v1/sales/chargebacks": {
        "get": {
          "operationId": "getmyeduzzv1saleschargebacks",
          "summary": "Obtém uma lista detalhada de chargebacks com base nos filtros fornecidos",
          "tags": [
            "MyEduzz"
          ],
          "security": [
            {
              "eduzz_auth": [
                "myeduzz_sales_read"
              ]
            }
          ]
        }
      },
      "/myeduzz/v1/sales/summary": {
        "get": {
          "operationId": "getmyeduzzv1salessummary",
          "summary": "Retorna um relatório sumarizado com o total realizado em vendas com base nos filtros fornecidos.",
          "tags": [
            "MyEduzz"
          ],
          "security": [
            {
              "eduzz_auth": [
                "myeduzz_sales_read"
              ]
            }
          ]
        }
      },
      "/nutror/v1/comments/:id": {
        "patch": {
          "operationId": "patchnutrorv1commentsid",
          "summary": "Altera estados do comentário.",
          "tags": [
            "Nutror"
          ],
          "security": [
            {
              "eduzz_auth": [
                "nutror_comments_write"
              ]
            }
          ]
        },
        "get": {
          "operationId": "getnutrorv1commentsid",
          "summary": "Busca por um comentário específico",
          "tags": [
            "Nutror"
          ],
          "security": [
            {
              "eduzz_auth": [
                "nutror_comments_read"
              ]
            }
          ]
        },
        "delete": {
          "operationId": "deletenutrorv1commentsid",
          "summary": "Deletar um comentário",
          "tags": [
            "Nutror"
          ],
          "security": [
            {
              "eduzz_auth": [
                "nutror_comments_write"
              ]
            }
          ]
        }
      },
      "/nutror/v1/answers/:id": {
        "delete": {
          "operationId": "deletenutrorv1answersid",
          "summary": "Deletar uma resposta",
          "tags": [
            "Nutror"
          ],
          "security": [
            {
              "eduzz_auth": [
                "nutror_comments_write"
              ]
            }
          ]
        }
      },
      "/nutror/v1/comments": {
        "get": {
          "operationId": "getnutrorv1comments",
          "summary": "Lista comentários",
          "tags": [
            "Nutror"
          ],
          "security": [
            {
              "eduzz_auth": [
                "nutror_comments_read"
              ]
            }
          ]
        }
      },
      "/nutror/v1/comments/:id/answers": {
        "get": {
          "operationId": "getnutrorv1commentsidanswers",
          "summary": "Lista respostas de comentário",
          "tags": [
            "Nutror"
          ],
          "security": [
            {
              "eduzz_auth": [
                "nutror_comments_read"
              ]
            }
          ]
        },
        "post": {
          "operationId": "postnutrorv1commentsidanswers",
          "summary": "Cria uma resposta para um comentário",
          "tags": [
            "Nutror"
          ],
          "security": [
            {
              "eduzz_auth": [
                "nutror_comments_write"
              ]
            }
          ]
        }
      },
      "/nutror/v1/courses/:courseId": {
        "get": {
          "operationId": "getnutrorv1coursescourseId",
          "summary": "Buscar por um curso em específico",
          "tags": [
            "Nutror"
          ],
          "security": [
            {
              "eduzz_auth": [
                "nutror_courses_read"
              ]
            }
          ]
        },
        "delete": {
          "operationId": "deletenutrorv1coursescourseId",
          "summary": "Deletar curso",
          "tags": [
            "Nutror"
          ],
          "security": [
            {
              "eduzz_auth": [
                "nutror_courses_write"
              ]
            }
          ]
        },
        "put": {
          "operationId": "putnutrorv1coursescourseId",
          "summary": "Editar as informações básicas de um curso",
          "tags": [
            "Nutror"
          ],
          "security": [
            {
              "eduzz_auth": [
                "nutror_courses_write"
              ]
            }
          ]
        }
      },
      "/nutror/v1/courses/:courseId/modules/:moduleId": {
        "get": {
          "operationId": "getnutrorv1coursescourseIdmodulesmoduleId",
          "summary": "Buscar por um módulo específico de um curso",
          "tags": [
            "Nutror"
          ],
          "security": [
            {
              "eduzz_auth": [
                "nutror_courses_read"
              ]
            }
          ]
        },
        "delete": {
          "operationId": "deletenutrorv1coursescourseIdmodulesmoduleId",
          "summary": "Deletar módulo",
          "tags": [
            "Nutror"
          ],
          "security": [
            {
              "eduzz_auth": [
                "nutror_courses_write"
              ]
            }
          ]
        },
        "put": {
          "operationId": "putnutrorv1coursescourseIdmodulesmoduleId",
          "summary": "Editar as informações de um módulo",
          "tags": [
            "Nutror"
          ],
          "security": [
            {
              "eduzz_auth": [
                "nutror_courses_write"
              ]
            }
          ]
        }
      },
      "/nutror/v1/courses/:courseId/advanced": {
        "put": {
          "operationId": "putnutrorv1coursescourseIdadvanced",
          "summary": "Editar as informações avançadas de um curso",
          "tags": [
            "Nutror"
          ],
          "security": [
            {
              "eduzz_auth": [
                "nutror_courses_write"
              ]
            }
          ]
        }
      },
      "/nutror/v1/courses/:courseId/customization": {
        "put": {
          "operationId": "putnutrorv1coursescourseIdcustomization",
          "summary": "Editar as informações de customização de um curso",
          "tags": [
            "Nutror"
          ],
          "security": [
            {
              "eduzz_auth": [
                "nutror_courses_write"
              ]
            }
          ]
        }
      },
      "/nutror/v1/courses": {
        "get": {
          "operationId": "getnutrorv1courses",
          "summary": "Listar todos cursos",
          "tags": [
            "Nutror"
          ],
          "security": [
            {
              "eduzz_auth": [
                "nutror_courses_read"
              ]
            }
          ]
        }
      },
      "/nutror/v1/courses/:courseId/modules": {
        "get": {
          "operationId": "getnutrorv1coursescourseIdmodules",
          "summary": "Listar todos módulos do curso",
          "tags": [
            "Nutror"
          ],
          "security": [
            {
              "eduzz_auth": [
                "nutror_courses_read"
              ]
            }
          ]
        }
      },
      "/nutror/v1/enrollments/:id/block": {
        "put": {
          "operationId": "putnutrorv1enrollmentsidblock",
          "summary": "Bloqueia o aluno",
          "tags": [
            "Nutror"
          ],
          "security": [
            {
              "eduzz_auth": [
                "nutror_my_students_write"
              ]
            }
          ]
        }
      },
      "/nutror/v1/enrollments/:id/extend-access": {
        "put": {
          "operationId": "putnutrorv1enrollmentsidextendaccess",
          "summary": "Estende o acesso do aluno",
          "tags": [
            "Nutror"
          ],
          "security": [
            {
              "eduzz_auth": [
                "nutror_my_students_write"
              ]
            }
          ]
        }
      },
      "/nutror/v1/students/:id": {
        "delete": {
          "operationId": "deletenutrorv1studentsid",
          "summary": "Exclui o aluno especificado pelo id",
          "tags": [
            "Nutror"
          ],
          "security": [
            {
              "eduzz_auth": [
                "nutror_my_students_write"
              ]
            }
          ]
        },
        "get": {
          "operationId": "getnutrorv1studentsid",
          "summary": "Perfil do aluno",
          "tags": [
            "Nutror"
          ],
          "security": [
            {
              "eduzz_auth": [
                "nutror_my_students_read"
              ]
            }
          ]
        }
      },
      "/nutror/v1/enrollments/:id/release-modules": {
        "put": {
          "operationId": "putnutrorv1enrollmentsidreleasemodules",
          "summary": "Libera os módulos do curso para o aluno matrículado",
          "tags": [
            "Nutror"
          ],
          "security": [
            {
              "eduzz_auth": [
                "nutror_my_students_write"
              ]
            }
          ]
        }
      },
      "/nutror/v1/students": {
        "get": {
          "operationId": "getnutrorv1students",
          "summary": "Listar alunos",
          "tags": [
            "Nutror"
          ],
          "security": [
            {
              "eduzz_auth": [
                "nutror_my_students_read"
              ]
            }
          ]
        }
      },
      "/nutror/v1/students/:id/enrollments": {
        "get": {
          "operationId": "getnutrorv1studentsidenrollments",
          "summary": "Lista matrículas do aluno",
          "tags": [
            "Nutror"
          ],
          "security": [
            {
              "eduzz_auth": [
                "nutror_my_students_read"
              ]
            }
          ]
        }
      },
      "/nutror/v1/enrollments/:id": {
        "delete": {
          "operationId": "deletenutrorv1enrollmentsid",
          "summary": "Remover a matrícula do aluno",
          "tags": [
            "Nutror"
          ],
          "security": [
            {
              "eduzz_auth": [
                "nutror_my_students_write"
              ]
            }
          ]
        }
      },
      "/safevideo/v1/medias/:id/domains": {
        "put": {
          "operationId": "putsafevideov1mediasiddomains",
          "summary": "Pode alterar os domínios permitidos da mídia",
          "tags": [
            "SafeVideo"
          ],
          "security": [
            {
              "eduzz_auth": [
                "safevideo_contents_write"
              ]
            }
          ]
        },
        "delete": {
          "operationId": "deletesafevideov1mediasiddomains",
          "summary": "Poder excluir os domínios da mídia",
          "tags": [
            "SafeVideo"
          ],
          "security": [
            {
              "eduzz_auth": [
                "safevideo_contents_write"
              ]
            }
          ]
        }
      },
      "/safevideo/v1/medias/:id": {
        "put": {
          "operationId": "putsafevideov1mediasid",
          "summary": "Pode alterar o título ou descrição da mídia",
          "tags": [
            "SafeVideo"
          ],
          "security": [
            {
              "eduzz_auth": [
                "safevideo_contents_write"
              ]
            }
          ]
        },
        "get": {
          "operationId": "getsafevideov1mediasid",
          "summary": "Detalhes da mídia do produtor",
          "tags": [
            "SafeVideo"
          ],
          "security": [
            {
              "eduzz_auth": [
                "safevideo_contents_read"
              ]
            }
          ]
        },
        "delete": {
          "operationId": "deletesafevideov1mediasid",
          "summary": "Excluir mídia especifica por id",
          "tags": [
            "SafeVideo"
          ],
          "security": [
            {
              "eduzz_auth": [
                "safevideo_contents_write"
              ]
            }
          ]
        }
      },
      "/safevideo/v1/medias/:id/embed": {
        "get": {
          "operationId": "getsafevideov1mediasidembed",
          "summary": "Poder adicionar a mídia em sites externos com link de embed",
          "tags": [
            "SafeVideo"
          ],
          "security": [
            {
              "eduzz_auth": [
                "safevideo_contents_read"
              ]
            }
          ]
        }
      },
      "/safevideo/v1/medias": {
        "get": {
          "operationId": "getsafevideov1medias",
          "summary": "Listagem com as mídias do produtor",
          "tags": [
            "SafeVideo"
          ],
          "security": [
            {
              "eduzz_auth": [
                "safevideo_contents_read"
              ]
            }
          ]
        }
      },
      "/webhook/v1/subscription/:subscriptionId": {
        "put": {
          "operationId": "putwebhookv1subscriptionsubscriptionId",
          "summary": "Alterar uma configuração (url que receberá os eventos) de webhook",
          "tags": [
            "Webhook"
          ],
          "security": [
            {
              "eduzz_auth": [
                "webhook_write"
              ]
            }
          ]
        }
      },
      "/webhook/v1/subscription": {
        "post": {
          "operationId": "postwebhookv1subscription",
          "summary": "Criar uma configuração (url que receberá os eventos) de webhook",
          "tags": [
            "Webhook"
          ],
          "security": [
            {
              "eduzz_auth": [
                "webhook_write"
              ]
            }
          ]
        },
        "delete": {
          "operationId": "deletewebhookv1subscription",
          "summary": "Deleta uma inscrição de WebHook por URL",
          "tags": [
            "Webhook"
          ],
          "security": [
            {
              "eduzz_auth": [
                "webhook_write"
              ]
            }
          ]
        },
        "get": {
          "operationId": "getwebhookv1subscription",
          "summary": "Lista Inscrições de Webhook",
          "tags": [
            "Webhook"
          ],
          "security": [
            {
              "eduzz_auth": [
                "webhook_read"
              ]
            }
          ]
        }
      },
      "/webhook/v1/subscription/:id": {
        "delete": {
          "operationId": "deletewebhookv1subscriptionid",
          "summary": "Deleta uma inscrição de WebHook por ID",
          "tags": [
            "Webhook"
          ],
          "security": [
            {
              "eduzz_auth": [
                "webhook_write"
              ]
            }
          ]
        }
      },
      "/webhook/v1/subscription/:id/status": {
        "post": {
          "operationId": "postwebhookv1subscriptionidstatus",
          "summary": "Habilita ou desabilita uma inscrição de webhook",
          "tags": [
            "Webhook"
          ],
          "security": [
            {
              "eduzz_auth": [
                "webhook_write"
              ]
            }
          ]
        }
      },
      "/webhook/v1/subscription/sample": {
        "post": {
          "operationId": "postwebhookv1subscriptionsample",
          "summary": "Requisita o envio do teste de um WebHook",
          "tags": [
            "Webhook"
          ],
          "security": [
            {
              "eduzz_auth": [
                "webhook_read"
              ]
            }
          ]
        }
      },
      "/webhook/v1/origin/sample/:event": {
        "get": {
          "operationId": "getwebhookv1originsampleevent",
          "summary": "Lista de exemplos dos eventos de webhooks disponíveis em cada origem",
          "tags": [
            "Webhook"
          ],
          "security": [
            {
              "eduzz_auth": []
            }
          ]
        }
      },
      "/webhook/v1/origin": {
        "get": {
          "operationId": "getwebhookv1origin",
          "summary": "Listar origens de webhook",
          "tags": [
            "Webhook"
          ],
          "security": [
            {
              "eduzz_auth": []
            }
          ]
        }
      },
      "/webhook/v1/secret": {
        "get": {
          "operationId": "getwebhookv1secret",
          "summary": "Retorna a secret de validação de webhooks criados pelo App",
          "tags": [
            "Webhook"
          ],
          "security": [
            {
              "eduzz_auth": [
                "webhook_read"
              ]
            }
          ]
        }
      }
    },
    "components": {
      "securitySchemes": {
        "eduzz_auth": {
          "type": "oauth2",
          "flows": {
            "implicit": {
              "authorizationUrl": "https://accounts.eduzz.com/oauth/authorize",
              "scopes": {}
            }
          }
        }
      }
    }
  }
}